apiVersion: v1
kind: Service
metadata:
  name: open-metadata-lb
  namespace: openmetadata
spec:
  selector:
    app.kubernetes.io/instance: openmetadata
    app.kubernetes.io/name: openmetadata
  ports:
    - port: 8585
  type: LoadBalancer